### ISSUE TITLE
Only one image on the Projects Page

### ISSUE THREAD

**Issue by OptionParalysis** [serkansokmen/sfolio#1]
Thanks for posting your code, it's really help me on trying to achieve what I am looking for.  Right now my issue/question is how can I get multiple images on the projects page?  Right now I'm only pulling one image and I have a couple in my Behance account loaded for public display.  Any help is greatly appreciated.

**Comment by serkansokmen** [comment]
This doesn't seem like an issue about the source code so i'll close it for now.

But you can make a query for every project (or the ones you wish for) via the Behance.js api and render responses using ng-repeat, but it would make the homepage slower, unless you make a chained request.

But as far as i know, as the current Behance platform works, projects page displays project thumbnails, not the content of the project page.

You can see a working demo of the project [here](http://fitoera.com).

**Comment by OptionParalysis** [comment]
I'm new to angularjs and api's, but what I'm trying to do is pull all of my
projects to be displayed as thumbnails on the projects.html page.  When you
click it goes to the project page like you have setup.  I just want one
page with all the projects displayed.  Any help would be huge and greatly
appreciate.

**Comment by serkansokmen** [comment]
You can check 'app/scripts/projects.js' which is a controller responsible for loading projects list, also 'app/scripts/project.js' contains project detail controller. They use 'app/scripts/services/behance.js' to interact with the [Behance API](https://www.behance.net/dev) using JSONP.

You can learn more about angular and controllers [here](https://code.angularjs.org/1.2.16/docs/guide/controller). Hope that this helps -)

**Comment by OptionParalysis** [comment]
Thank you sooo much.  I hope I haven't been a bother, but I really
appreciate it.

-Zach

**Comment by serkansokmen** [comment]
Of course you didn't, let me know if you have any problems / success.

Take care.
